function list = supportedcontrols(),
%SUPPORTEDCONTROLS - list the control parameters supported by ISSM inversions
%
%   Usage:
%      list=supportedcontrols()

	list = {...
		'BalancethicknessThickeningRate',...
		'FrictionCoefficient',...
		'FrictionC',...
		'FrictionAs',...
		'MaterialsRheologyBbar',...
		'DamageDbar',...
		'Vx',...
		'Vy',...
		'Thickness',...
		'BalancethicknessOmega',...
		'BalancethicknessApparentMassbalance',...
		'MaterialsRheologyB'};
