declare -x ALLUSERSPROFILE="C:\\ProgramData"
declare -x ARCH_PATH="intel64"
declare -x ARCH_PATH_MPI="em64t"
declare -x BIN_ROOT="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\bin\\"
declare -x BUNDLE_NAME="Intel Parallel Studio XE 2011 SP1"
declare -x COMMONPROGRAMFILES="C:\\Program Files (x86)\\Common Files"
declare -x COMPUTERNAME="WIN-HR4P7FV3HFA"
declare -x COMSPEC="C:\\Windows\\system32\\cmd.exe"
declare -x CPRO_PATH="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1"
declare -x C_EM64T_REDIST12="C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\"
declare -x C_TARGET_ARCH="intel64"
declare -x CommonProgramW6432="C:\\Program Files\\Common Files"
declare -x DISPLAY=":0"
declare -x DevEnvDir="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\IDE\\"
declare -x FP_NO_HOST_CHECK="NO"
declare -x F_EM64T_REDIST12="C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\"
declare -x F_IA32_REDIST12="C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\"
declare -x Framework35Version="v3.5"
declare -x FrameworkDIR32="C:\\Windows\\Microsoft.NET\\Framework\\"
declare -x FrameworkDir="C:\\Windows\\Microsoft.NET\\Framework\\"
declare -x FrameworkVersion="v4.0.30319"
declare -x FrameworkVersion32="v4.0.30319"
declare -x GREP_COLOR="00;38;5;226"
declare -x GREP_OPTIONS="--binary-file=without-match"
declare -x HOMEDRIVE="C:"
declare -x ICPP_COMPILER12="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\"
declare -x IFORT_COMPILER12="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\"
declare -x INCLUDE="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\compiler\\include;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\compiler\\include\\intel64;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\atlmfc\\include;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\include;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\include;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\ipp\\include;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\mkl\\include;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\tbb\\bin\\..\\include;"
declare -x INFOPATH="/usr/local/info:/usr/share/info:/usr/info:"
declare -x INTEL_LICENSE_FILE="C:\\Program Files (x86)\\Common Files\\Intel\\Licenses"
declare -x IPPROOT="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\ipp"
declare -x IPP_TARGET_ARCH="intel64"
declare -x J2D_D3D="false"
declare -x LANG="C.UTF-8"
declare -x LIB="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\compiler\\lib;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\compiler\\lib\\intel64;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\lib\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\lib\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\lib\\x64\\;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC\\PlatformSDK\\lib\\x64\\;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\ipp\\lib\\intel64;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\ipp\\..\\compiler\\lib\\intel64;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\mkl\\lib\\intel64;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\compiler\\lib\\intel64;C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\tbb\\bin\\..\\lib\\intel64\\vc10;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB;"
declare -x LIBPATH="C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Windows\\Microsoft.NET\\Framework\\v3.5;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB;"
declare -x MANPATH="/usr/local/man:/usr/share/man:/usr/man:"
declare -x MATLAB_DIR="C:/MATLAB/R2011b"
declare -x MKLROOT="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\mkl"
declare -x MKL_LP64_ILP64="lp64"
declare -x MKL_TARGET_ARCH="intel64"
declare -x MOD_NAME="mod"
declare -x MPIRUN_NPROCS="24"
declare -x MSVS_VAR_SCRIPT="\"C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\bin\\vsshell2010vars_arch.bat\""
declare -x NUMBER_OF_PROCESSORS="1"
declare -x OS="Windows_NT"
declare -x PATH="/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/bin/intel64:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/compiler:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Intel Fortran/Microsoft Files/VC/BIN/x86_amd64:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools/bin:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Intel Fortran/Microsoft Files/VC/bin:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/ipp:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/compiler:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/mkl:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/compiler:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/tbb/vc10:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/ia32/mkl:/cygdrive/c/Program Files (x86)/Common Files/Microsoft Shared/VSA/10.0/VsaEnv:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/mpirt:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32/mpirt:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/ia32/compiler:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/ipp:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/mkl:/cygdrive/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/MATLAB/R2011b/runtime/win64:/cygdrive/c/Program Files/MATLAB/R2011b/bin:/cygdrive/c/Program Files (x86)/Intel/Composer XE 2011 SP1/redist/intel64/mpirt"
declare -x PATHEXT=".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
declare -x PLATFORM="x86-Linux"
declare -x PRINTER="Microsoft XPS Document Writer"
declare -x PROCESSOR_ARCHITECTURE="x86"
declare -x PROCESSOR_ARCHITEW6432="AMD64"
declare -x PROCESSOR_IDENTIFIER="Intel64 Family 6 Model 44 Stepping 2, GenuineIntel"
declare -x PROCESSOR_LEVEL="6"
declare -x PROCESSOR_REVISION="2c02"
declare -x PRODUCT_NAME="Intel Composer XE 2011 "
declare -x PRODUCT_NAME_FULL="Intel Composer XE 2011 Update 8 (package 278)"
declare -x PROGRAMFILES="C:\\Program Files (x86)"
declare -x PROMPT="\$P\$G"
declare -x PS1="\\[\\e]0;\\w\\a\\]\\n\\[\\e[32m\\]\\u@\\h \\[\\e[33m\\]\\w\\[\\e[0m\\]\\n\\\$ "
declare -x PSModulePath="C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\"
declare -x PUBLIC="C:\\Users\\Public"
declare -x ProgramData="C:\\ProgramData"
declare -x ProgramW6432="C:\\Program Files"
declare -x QMAKESPEC="cygwin-g++"
declare -x REDIST="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\redist"
declare -x REPO="jpl"
declare -x ROOT="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1"
declare -x SCRIPT_NAME="compilervars_arch.bat"
declare -x SDK_DIR
declare -x SESSIONNAME="Console"
declare -x SHELL="/bin/bash"
declare -x SHLVL="5"
declare -x STY="1784.tty3.WIN-HR4P7FV3HFA"
declare -x SYSTEMDRIVE="C:"
declare -x SYSTEMROOT="C:\\Windows"
declare -x TARGET_ARCH="intel64"
declare -x TARGET_VS="vs2010"
declare -x TARGET_VS_ARCH="amd64"
declare -x TBBROOT="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\tbb\\bin\\.."
declare -x TBB_ARCH_PLATFORM="intel64\\vc10"
declare -x TBB_BIN_DIR="C:\\Program Files (x86)\\Intel\\Composer XE 2011 SP1\\tbb\\bin\\"
declare -x TBB_CXX="icl.exe"
declare -x TBB_TARGET_ARCH="intel64"
declare -x TBB_TARGET_VS="vc10"
declare -x TEMP="/tmp"
declare -x TERM="screen"
declare -x TERMCAP="SC|screen|VT 100/ANSI X3.64 virtual terminal:\\
	:DO=\\E[%dB:LE=\\E[%dD:RI=\\E[%dC:UP=\\E[%dA:bs:bt=\\E[Z:\\
	:cd=\\E[J:ce=\\E[K:cl=\\E[H\\E[J:cm=\\E[%i%d;%dH:ct=\\E[3g:\\
	:do=^J:nd=\\E[C:pt:rc=\\E8:rs=\\Ec:sc=\\E7:st=\\EH:up=\\EM:\\
	:le=^H:bl=^G:cr=^M:it#8:ho=\\E[H:nw=\\EE:ta=^I:is=\\E)0:\\
	:li#71:co#217:am:xn:xv:LP:sr=\\EM:al=\\E[L:AL=\\E[%dL:\\
	:cs=\\E[%i%d;%dr:dl=\\E[M:DL=\\E[%dM:dc=\\E[P:DC=\\E[%dP:\\
	:im=\\E[4h:ei=\\E[4l:mi:IC=\\E[%d@:ks=\\E[?1h\\E=:\\
	:ke=\\E[?1l\\E>:vi=\\E[?25l:ve=\\E[34h\\E[?25h:vs=\\E[34l:\\
	:ti=\\E[?1049h:te=\\E[?1049l:us=\\E[4m:ue=\\E[24m:so=\\E[3m:\\
	:se=\\E[23m:mb=\\E[5m:md=\\E[1m:mr=\\E[7m:me=\\E[m:ms:\\
	:Co#8:pa#64:AF=\\E[3%dm:AB=\\E[4%dm:op=\\E[39;49m:AX:\\
	:vb=\\Eg:G0:as=\\E(0:ae=\\E(B:\\
	:ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\\
	:po=\\E[5i:pf=\\E[4i:k0=\\E[10~:k1=\\EOP:k2=\\EOQ:k3=\\EOR:\\
	:k4=\\EOS:k5=\\E[15~:k6=\\E[17~:k7=\\E[18~:k8=\\E[19~:\\
	:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:F3=\\E[1;2P:\\
	:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:F7=\\E[15;2~:\\
	:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:kb=:K2=\\EOE:\\
	:kB=\\E[Z:kF=\\E[1;2B:kR=\\E[1;2A:*4=\\E[3;2~:*7=\\E[1;2F:\\
	:#2=\\E[1;2H:#3=\\E[2;2~:#4=\\E[1;2D:%c=\\E[6;2~:%e=\\E[5;2~:\\
	:%i=\\E[1;2C:kh=\\E[1~:@1=\\E[1~:kH=\\E[4~:@7=\\E[4~:\\
	:kN=\\E[6~:kP=\\E[5~:kI=\\E[2~:kD=\\E[3~:ku=\\EOA:kd=\\EOB:\\
	:kr=\\EOC:kl=\\EOD:km:"
declare -x TMP="/tmp"
declare -x USER="larour"
declare -x USERDOMAIN="WIN-HR4P7FV3HFA"
declare -x USERNAME="larour"
declare -x USERPROFILE="C:\\Users\\larour"
declare -x VCINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\\\Intel Fortran\\Microsoft Files\\VC"
declare -x VS100COMNTOOLS="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\"
declare -x VSINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\"
declare -x VSSHELL2010INSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\"
declare -x WINDIR="C:\\Windows"
declare -x WINDOW="0"
declare -x WINDOWID="10485795"
declare -x WIN_TITLE="Intel Composer XE 2011  Intel(R) 64 Visual Studio 2010"
declare -x WIN_TITLE_ARCH="Intel(R) 64"
declare -x WIN_TITLE_VS="Visual Studio 2010"
declare -x WindowsSdkDir="C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\"
declare -x XTERM_LOCALE="C.UTF-8"
declare -x XTERM_SHELL="/bin/bash"
declare -x XTERM_VERSION="XTerm(276)"
declare -x windows_tracing_flags="3"
declare -x windows_tracing_logfile="C:\\BVTBin\\Tests\\installpackage\\csilogfile.log"
