/*
 * analyses.h:
 */

#ifndef _ANALYSES_H_
#define _ANALYSES_H_

#include "./Analysis.h"

#include "./AdjointBalancethicknessAnalysis.h"
#include "./AdjointBalancethickness2Analysis.h"
#include "./AdjointHorizAnalysis.h"
#include "./AgeAnalysis.h"
#include "./BalancethicknessAnalysis.h"
#include "./Balancethickness2Analysis.h"
#include "./BalancethicknessSoftAnalysis.h"
#include "./BalancevelocityAnalysis.h"
#include "./DamageEvolutionAnalysis.h"
#include "./DebrisAnalysis.h"
#include "./DepthAverageAnalysis.h"
#include "./EnthalpyAnalysis.h"
#include "./ExtrudeFromBaseAnalysis.h"
#include "./ExtrudeFromTopAnalysis.h"
#include "./ExtrapolationAnalysis.h"
#include "./FreeSurfaceBaseAnalysis.h"
#include "./FreeSurfaceTopAnalysis.h"
#include "./GLheightadvectionAnalysis.h"
#include "./LoveAnalysis.h"
#include "./EsaAnalysis.h"
#include "./HydrologyArmapwAnalysis.h"
#include "./HydrologyDCEfficientAnalysis.h"
#include "./HydrologyDCInefficientAnalysis.h"
#include "./HydrologyShreveAnalysis.h"
#include "./HydrologyTwsAnalysis.h"
#include "./HydrologyGlaDSAnalysis.h"
#include "./HydrologyShaktiAnalysis.h"
#include "./HydrologyPismAnalysis.h"
#include "./LevelsetAnalysis.h"
#include "./MasstransportAnalysis.h"
#include "./OceantransportAnalysis.h"
#include "./SamplingAnalysis.h"
#include "./SmbAnalysis.h"
#include "./SealevelchangeAnalysis.h"
#include "./MeltingAnalysis.h"
#include "./SmoothAnalysis.h"
#include "./StressbalanceAnalysis.h"
#include "./StressbalanceSIAAnalysis.h"
#include "./StressbalanceVerticalAnalysis.h"
#include "./UzawaPressureAnalysis.h"
#include "./L2ProjectionBaseAnalysis.h"
#include "./L2ProjectionEPLAnalysis.h"
#include "./ThermalAnalysis.h"
#include "./EnumToAnalysis.h"
#endif
